### ISSUE TITLE
x86 build?

### ISSUE THREAD

**Issue by PM250B** [bytespiller/sidplaywx#5]
Is a x86 build possible?

**Comment by bytespiller** [comment]
You mean 32 bit build? I've never tried it but I don't think there is anything in sidplaywx or its dependencies that inherently requires a 64 bit OS.

Not sure how fiddly it would be to setup building a 32 bit application on 64 bit host OS though.

**Comment by bytespiller** [comment]
I currently have no plans to include 32-bit Windows builds in the releases.

I've recently ([v0.13.0](https://github.com/bytespiller/sidplaywx/releases/tag/v0.13.0)) switched to the modern UCRT64 environment for building Windows releases of the sidplaywx, so setting up and troubleshooting a separate 32 bit legacy build environment (also implying Windows XP support) seems like an extra complication with limited benefit.
