### ISSUE TITLE
sc68 file format

### ISSUE THREAD

**Issue by heretik3d** [bytespiller/sidplaywx#6]
Hey, can you add support for sc68 format? Theres a lot of amazing music in sc68.atari.org but no player... (except old winamp with sc68 plugin and some webpages that offer online player but it is not way I like...). Thank you for considering my suggestion.

**Comment by bytespiller** [comment]
It seems an actively maintained GUI player for this already exists, I've tried it and it works nicely and sounds great: https://github.com/arnaud-neny/rePlayer

**Comment by heretik3d** [comment]
.
